<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="wwwroot\lib\ckeditor\.npm\assets\ckeditor4.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\site.js" />
    <None Include="wwwroot\lib\bootstrap-colorpicker\.github\CODE_OF_CONDUCT.md" />
    <None Include="wwwroot\lib\bootstrap-colorpicker\.github\CONTRIBUTING.md" />
    <None Include="wwwroot\lib\bootstrap-colorpicker\.github\ISSUE_TEMPLATE.md" />
    <None Include="wwwroot\lib\bootstrap-colorpicker\.github\PULL_REQUEST_TEMPLATE.md" />
    <None Include="wwwroot\lib\bootstrap-datepicker\.github\ISSUE_TEMPLATE.md" />
    <None Include="wwwroot\lib\bootstrap-datepicker\.github\PULL_REQUEST_TEMPLATE.md" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\LICENSE" />
    <None Include="wwwroot\lib\bootstrap\README.md" />
    <None Include="wwwroot\lib\bootstrap\scss\bootstrap-grid.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\bootstrap-reboot.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\bootstrap.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_alert.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_background-variant.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_badge.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_border-radius.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_box-shadow.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_breakpoints.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_buttons.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_caret.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_clearfix.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_deprecate.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_float.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_forms.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_gradients.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_grid-framework.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_grid.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_hover.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_image.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_list-group.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_lists.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_nav-divider.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_pagination.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_reset-text.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_resize.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_screen-reader.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_size.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_table-row.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_text-emphasis.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_text-hide.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_text-truncate.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_transition.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\mixins\_visibility.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_align.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_background.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_borders.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_clearfix.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_display.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_embed.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_flex.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_float.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_overflow.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_position.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_screenreaders.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_shadows.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_sizing.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_spacing.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_stretched-link.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_text.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\utilities\_visibility.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\vendor\_rfs.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_alert.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_badge.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_breadcrumb.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_button-group.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_buttons.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_card.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_carousel.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_close.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_code.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_custom-forms.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_dropdown.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_forms.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_functions.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_grid.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_images.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_input-group.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_jumbotron.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_list-group.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_media.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_mixins.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_modal.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_nav.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_navbar.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_pagination.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_popover.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_print.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_progress.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_reboot.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_root.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_spinners.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_tables.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_toasts.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_tooltip.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_transitions.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_type.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_utilities.scss" />
    <None Include="wwwroot\lib\bootstrap\scss\_variables.scss" />
    <None Include="wwwroot\lib\ckeditor\.github\ISSUE_TEMPLATE" />
    <None Include="wwwroot\lib\ckeditor\.npm\README.md" />
    <None Include="wwwroot\lib\datatables\js\dataTables.bootstrap.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.bootstrap.min.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.bootstrap4.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.bootstrap4.min.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.dataTables.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.dataTables.min.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.foundation.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.foundation.min.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.jqueryui.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.jqueryui.min.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.material.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.material.min.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.semanticui.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.semanticui.min.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.uikit.js" />
    <None Include="wwwroot\lib\datatables\js\dataTables.uikit.min.js" />
    <None Include="wwwroot\lib\datatables\js\jquery.dataTables.js" />
    <None Include="wwwroot\lib\datatables\js\jquery.dataTables.min.js" />
    <None Include="wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.js" />
    <None Include="wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.min.js" />
    <None Include="wwwroot\lib\jquery-validation\dist\additional-methods.js" />
    <None Include="wwwroot\lib\jquery-validation\dist\additional-methods.min.js" />
    <None Include="wwwroot\lib\jquery-validation\dist\jquery.validate.js" />
    <None Include="wwwroot\lib\jquery-validation\dist\jquery.validate.min.js" />
    <None Include="wwwroot\lib\jquery-validation\LICENSE.md" />
    <None Include="wwwroot\lib\jquery\dist\jquery.js" />
    <None Include="wwwroot\lib\jquery\dist\jquery.min.js" />
    <None Include="wwwroot\lib\jquery\dist\jquery.min.map" />
    <None Include="wwwroot\lib\jquery\dist\jquery.slim.js" />
    <None Include="wwwroot\lib\jquery\dist\jquery.slim.min.js" />
    <None Include="wwwroot\lib\jquery\dist\jquery.slim.min.map" />
    <None Include="wwwroot\lib\jquery\README.md" />
    <None Include="wwwroot\lib\jvectormap\jquery-jvectormap-1.2.2.min.js" />
    <None Include="wwwroot\lib\jvectormap\jquery-jvectormap-usa-en.js" />
    <None Include="wwwroot\lib\jvectormap\jquery-jvectormap-world-mill-en.js" />
    <None Include="wwwroot\lib\PACE\pace.js" />
    <None Include="wwwroot\lib\PACE\pace.min.js" />
    <None Include="wwwroot\lib\seiyria-bootstrap-slider\bootstrap-slider.js" />
    <None Include="wwwroot\lib\seiyria-bootstrap-slider\bootstrap-slider.min.js" />
    <None Include="wwwroot\lib\select2\.github\CONTRIBUTING.md" />
    <None Include="wwwroot\lib\select2\.github\ISSUE_TEMPLATE.md" />
    <None Include="wwwroot\lib\select2\.github\PULL_REQUEST_TEMPLATE.md" />
    <None Include="wwwroot\lib\select2\.github\stale.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Azure.Identity" Version="1.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.2" />
    <PackageReference Include="NuGet.Common" Version="6.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EShop.AutoMapper\EShop.AutoMapper.csproj" />
    <ProjectReference Include="..\EShop.IdentityService\EShop.IdentityService.csproj" />
    <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj" />
    <ProjectReference Include="..\EShop.Log\EShop.LogService.csproj" />
    <ProjectReference Include="..\EShop.Model\EShop.Model.csproj" />
    <ProjectReference Include="..\EShop.Repository\EShop.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\BasicInfo\" />
    <Folder Include="Pages\Supplier\" />
    <Folder Include="wwwroot\img\" />
    <Folder Include="wwwroot\lib\adminlte\dist\css\alt\" />
    <Folder Include="wwwroot\lib\adminlte\dist\css\skins\" />
    <Folder Include="wwwroot\lib\adminlte\dist\font\" />
    <Folder Include="wwwroot\lib\adminlte\dist\img\credit\" />
    <Folder Include="wwwroot\lib\adminlte\dist\js\pages\" />
  </ItemGroup>

</Project>
