<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Azure.Identity" Version="1.11.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EShop.AutoMapper\EShop.AutoMapper.csproj" />
    <ProjectReference Include="..\EShop.IdentityService\EShop.IdentityService.csproj" />
    <ProjectReference Include="..\EShop.Infrastructure\EShop.Infrastructure.csproj" />
    <ProjectReference Include="..\EShop.Log\EShop.LogService.csproj" />
    <ProjectReference Include="..\EShop.Repository\EShop.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Files\" />
  </ItemGroup>

</Project>
