<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Action.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Action.resx</DependentUpon>
    </Compile>
    <Compile Update="Errors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Errors.resx</DependentUpon>
    </Compile>
    <Compile Update="General.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>General.resx</DependentUpon>
    </Compile>
    <Compile Update="Notifications.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Notifications.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Action.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Action.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Errors.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Errors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="General.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>General.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Notifications.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Notifications.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
